apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::191353825293:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-8SACA582G2UA
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::191353825293:role/UdacityFlaskDeployCBKubectlRole
      username: build
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2020-09-04T22:51:44Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "19619"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: cf47a9b0-1ed7-4e1f-9cc9-2353867facf4
