apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::191353825293:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-1N2EACJXWZV4T
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2020-09-05T13:20:29Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1484"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: 7eb07c89-2d1e-48a4-96c3-ee9dd60d8cea
